# Aula 15 – Agrupamentos e Agregações

## Objetivo

Aprender a agrupar dados e gerar análises usando **groupby()**.

Tópicos:
- groupby()
- agg()
- múltiplas métricas
- reset_index()
- ordenação
- interpretação

In [30]:
import pandas as pd
import numpy as np

## Leitura da base

Preencha com sua base de vendas.

In [2]:
arquivo = r"C:\Users\Joao.Maria\Documents\curso-python_joao_pedro\Base\Base_analitica_vendas.xlsx"

base = pd.read_excel(arquivo, sheet_name="Base")

## Métricas de Agregação (Groupby)

### Básicas:
* **count()** -> Calcula o número de valores não nulos em cada grupo.
* **size()** -> Retorna o tamanho total do grupo (incluindo valores nulos).
* **sum()** -> Soma todos os valores do grupo.
* **mean()** -> Calcula a média aritmética simples.
* **median()** -> Retorna a mediana (valor central) do grupo.

### Dispersão e Estátistica:

* **min()** -> Identifica o valor mínimo dentro do grupo.
* **max()** -> Identifica o valor máximo dentro do grupo.
* **std()** -> Calcula o desvio padrão (o quanto os dados se afastam da média).
* **var()** -> Calcula a variância dos dados.
* **quantile(q)** -> Retorna o valor em um determinado quantil (ex: 0.25 para o 1º quartil).

### Seleção e Unidade:

* **nunique()** -> Conta quantos valores distintos (únicos) existem no grupo.
* **first()** -> Retorna o primeiro valor de cada grupo conforme a ordem do índice.
* **last()** -> Retorna o último valor de cada grupo.
* **unique()** -> Retorna uma lista com todos os elementos únicos do grupo.

# 1. Qual cliente mais fatura?

In [23]:
clientes = base.groupby("DESCRICAOCLIENTE")["VALORLIQUIDO"].sum()
clientes.sort_values(ascending=False).head()

clientes.head()

DESCRICAOCLIENTE
ATACADISTA BRINDE AMIGO          4295470.68
ATACADISTA BRINDE FINO            566415.28
ATACADISTA BRINDE SUPREMO         301509.72
ATACADISTA SELEÇÃO DE BEBIDAS    5406854.63
ATACADO BRINDE & CIA             2387934.45
Name: VALORLIQUIDO, dtype: float64

# 2. Agrupamento com múltiplas métricas

In [21]:
base.columns

Index(['DATAEMISSAO', 'CODIGOCLIENTE', 'DESCRICAOCLIENTE',
       'CODIGOGRUPOPRODUTO', 'DESCRICAOGRUPOPRODUTO', 'CODIGOPRODUTO',
       'NOMEPRODUTO', 'TIPOFATURAMENTO', 'DESCRICAOTIPOFATURAMENTO', 'VOLUME',
       'VALORLIQUIDO'],
      dtype='str')

In [29]:
clientes = (
    base.groupby("DESCRICAOCLIENTE")
    .agg({
        "VALORLIQUIDO": "sum",
        "VOLUME": "sum"
    })
)

clientes.head()

                               VALORLIQUIDO  VOLUME
DESCRICAOCLIENTE
ATACADISTA BRINDE AMIGO          4295470.68   48432
ATACADISTA BRINDE FINO            566415.28    6917
ATACADISTA BRINDE SUPREMO         301509.72    2321
ATACADISTA SELEÇÃO DE BEBIDAS    5406854.63   44891
ATACADO BRINDE & CIA             2387934.45   31817

# 3. Múltiplas métricas na mesma coluna

In [31]:
base.groupby("DESCRICAOCLIENTE")["VALORLIQUIDO"].agg(["sum","mean","max"]).head()

                                      sum         mean        max
DESCRICAOCLIENTE
ATACADISTA BRINDE AMIGO        4295470.68  3219.993013   53096.13
ATACADISTA BRINDE FINO          566415.28  1258.700622   18888.50
ATACADISTA BRINDE SUPREMO       301509.72  1945.224000   18715.30
ATACADISTA SELEÇÃO DE BEBIDAS  5406854.63  3915.173519  301339.00
ATACADO BRINDE & CIA           2387934.45  2176.786190  233305.80

# 4. Resetando índice

In [11]:
clientes = base.groupby("DESCRICAOCLIENTE")["VALORLIQUIDO"].sum().reset_index()
clientes.head()

                DESCRICAOCLIENTE  VALORLIQUIDO
0        ATACADISTA BRINDE AMIGO    4295470.68
1         ATACADISTA BRINDE FINO     566415.28
2      ATACADISTA BRINDE SUPREMO     301509.72
3  ATACADISTA SELEÇÃO DE BEBIDAS    5406854.63
4           ATACADO BRINDE & CIA    2387934.45

# 5. Ordenação

In [33]:
clientes.sort_values(by="VALORLIQUIDO", ascending=False).head()

                                 VALORLIQUIDO  VOLUME
DESCRICAOCLIENTE
LOGÍSTICA ESSENCIAL BEBIDAS        9166375.86   85530
DISTRIBUIDORA VIDA DE BEBIDA       6826258.29   41968
LOGÍSTICA BEBIDAS DO BRASIL        6655005.04   70998
DISTRIBUIDORA REINO DAS BEBIDAS    6020606.70   76703
DISTRIBUIDORA BRINDE & AMIGOS      5877731.95   41740

# 6. Agrupamento por múltiplas colunas

In [14]:
base.groupby(["DESCRICAOCLIENTE","TIPOFATURAMENTO"])["VALORLIQUIDO"].sum().reset_index().head(10)

                DESCRICAOCLIENTE  TIPOFATURAMENTO  VALORLIQUIDO
0        ATACADISTA BRINDE AMIGO                1    4321496.04
1        ATACADISTA BRINDE AMIGO                2     -33592.08
2        ATACADISTA BRINDE AMIGO                3       7566.72
3         ATACADISTA BRINDE FINO                1     576470.93
4         ATACADISTA BRINDE FINO                2     -10055.65
5         ATACADISTA BRINDE FINO                3          0.00
6      ATACADISTA BRINDE SUPREMO                1     223404.82
7      ATACADISTA BRINDE SUPREMO                3      20293.98
8      ATACADISTA BRINDE SUPREMO               13      57810.92
9  ATACADISTA SELEÇÃO DE BEBIDAS                1    3456056.54

# 7. Produto que mais gera receita

In [34]:
base.groupby(["NOMEPRODUTO"])["VALORLIQUIDO"].sum().sort_values(ascending=False).reset_index().head()

                        NOMEPRODUTO  VALORLIQUIDO
0  Cerveja Puro Malte Premium 355ml   13800420.58
1          Drink Misto Senses 269ml   13256991.98
2        Drink Misto Melancia 269ml   12828144.02
3        Drink Misto Maracujá 269ml   12434458.92
4       Drink Misto Blueberry 330ml    6254728.27